[package]
name = "day09"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = {path="../utils"}
ufmt-stdio = "0"
mos-alloc = "0.2.0"

[target.'cfg(target_vendor = "atari8")'.dependencies]
volatile-register = "0.2"
a800xl-utils = "0.2"
